### ISSUE TITLE
How to enter channel with pass register?

### ISSUE THREAD

**Issue by Atorcha** [Fredi/ArduinoIRC#4]
I will like to enterró IRC channel with my register user into a channel. Then I will monitorized the messages and when a messages be the same a text, for example "help" then a led will turn ON and I will enter.

In the same way I will like to send some predefined text with buttons.

What do you think about this?

**Comment by fredimachado** [comment]
Hey mate!
You can use the `JOIN` message passing the name of the channel and the password, like this:
`client.sendRaw("JOIN #channel p@ssw0rd");`
You can use this as a base: https://github.com/fredimachado/ArduinoIRC/blob/master/examples/ESP8266/BasicESP8266Reply/BasicESP8266Reply.ino
Just add your conditions and it should work fine.

Cheers!

**Comment by Atorcha** [comment]
OK I will try it.

Then I need to compare the text string and if in the text there are something like "Plattaform: XB" then It will turn on a LED Green...

I hope that I can do that...

**Comment by Atorcha** [comment]
I can not join. It says that:

Attempting IRC connection...
SENT: HELLO
SENT: NICK AnakinO7[XB]
SENT: USER AnakinO7[XB] 8 * :Arduino IRC Client
connected
:irc.de.eu.fuelrats.com 451 HELLO :You have not registered
:irc.de.eu.fuelrats.com 433 * AnakinO7[XB] :Nickname is already in use.
ERROR :Closing Link: [188.86.51.250] (Registration Timeout)


This is my nickname and I introduce my password.

**Comment by fredimachado** [comment]
Try a different nickname. But make sure you are not already connected using the same nickname.
